from __future__ import annotations as __future_annotations__

import json
import logging
from functools import cache
from pathlib import Path

from ...detector import (
    Devices,
    ManufacturerEnum,
    detect_devices,
    filter_devices_by_manufacturer,
)
from ...detector.ascend import get_ascend_cann_variant
from .__types__ import (
    Config,
    ConfigContainerEdits,
    ConfigDevice,
    Generator,
    manufacturer_to_cdi_kind,
    manufacturer_to_runtime_env,
)
from .__utils__ import (
    device_to_cdi_device_node,
    glob_to_cdi_mounts,
    path_to_cdi_device_nodes,
    path_to_cdi_mount,
)

logger = logging.getLogger(__name__)

_A5_CANN_VARIANT = "950"
"""
The CANN variant of the A5 generation, whose UB fabric replaces what the
earlier generations reach through the shared memory device.
"""

_HCCL_RANKTABLE_PATH = "/etc/hccl_rootinfo.json"
"""
The host ranktable ("rootinfo") file. Optional, user-maintained state: it
belongs to no driver package, and the vendor documents it as generated by
mindcluster-tools and mounted only when present, see
https://gitcode.com/Ascend/mind-cluster/blob/master/docs/en/scheduling/references/appendix.md.
"""

_HCCN_CONF_PATH = "/etc/hccn.conf"
"""
The device NIC addresses, as configured on the host. A transport that builds
RoCE endpoints reads them from this file or from hccn_tool, which lives in a
driver directory none of the mounts below covers; without either, the engine
fails to initialize with "Failed to get device ip from hccn.conf and
hccn_tool". A container that talks to another node over Device RoCE therefore
needs this file, and one that does not is unaffected by its presence.
"""

_A5_RANKTABLE_VERSION = "2.0"
"""
The ranktable version the A5 generation requires.

The format is bound to the chip generation -- 1.0 for A2, 1.2 for A3, 2.0 for
A5, see ascend-operator/pkg/ranktable/common/common.go:37-38 and
ranktable/v2dot0/ranktable.go:27. A5 loads libhccl_v2.so, which rejects an
older table outright rather than ignoring it.

Only the A5 row of that mapping has a measured failure behind it, so only A5 is
acted on. An A3 host carrying a 1.2 table is presumed correct rather than
warned about, because nothing here established otherwise.
"""

_A5_UB_MOUNT_PATTERNS = [
    "/usr/lib64/libummu*",
    "/usr/lib64/liburma*",
    "/usr/lib64/urma",
    "/usr/lib64/libnl*",
    "/usr/bin/urma_admin",
    "/usr/bin/urma_perftest",
    "/usr/bin/urma_ping",
]
"""
The UB user-space libraries an A5 container needs, mirroring the operator's
mount profile for the Ascend950 generation, see
https://gitcode.com/Ascend/mind-cluster/blob/master/component/ascend-common/cdi/mount/profile.go.

These are mounted for the A5 generation only. Some of them -- libnl above all
-- are ordinary system libraries present on any host, so mounting them
unconditionally would shadow what an earlier generation's container ships with
its own image.

The /usr/lib64 prefix is the operator's, and holds on the openEuler and CentOS
hosts an A5 ships on; a Debian-derived host uses /usr/lib/<triplet>, where none
of these match -- hence the log line when a pattern finds nothing.
"""


class AscendGenerator(Generator):
    """
    CDI generator for Ascend devices.
    """

    def __init__(self):
        super().__init__(ManufacturerEnum.ASCEND)

    def generate(
        self,
        devices: Devices | None = None,
        include_all_devices: bool = True,
    ) -> Config | None:
        """
        Generate the CDI configuration for Ascend devices.

        Args:
            devices:
                The detected devices.
                If None, all available devices are considered.
            include_all_devices:
                Whether to include a device entry that represents all Ascend devices.

        Returns:
            The Config object, or None if not supported.

        """
        if devices is None:
            devices = detect_devices(manufacturer=self.manufacturer)
        else:
            devices = filter_devices_by_manufacturer(
                devices,
                manufacturer=self.manufacturer,
            )

        if not devices:
            return None

        kind = manufacturer_to_cdi_kind(self.manufacturer)
        if not kind:
            return None

        common_device_nodes = []
        for p in [
            "/dev/davinci_manager_docker",
            "/dev/davinci_manager",
        ]:
            cdn = device_to_cdi_device_node(
                path=p,
                container_path="/dev/davinci_manager",
            )
            if cdn:
                common_device_nodes.append(cdn)
                break
        for p in [
            "/dev/dvpp_cmdlist",
            # UB exposes a directory of device nodes rather than a single one,
            # so every entry below it has to be injected.
            "/dev/uburma",
            "/dev/ummu",
            "/dev/devmm_svm",
            "/dev/hisi_hdc",
        ]:
            common_device_nodes.extend(path_to_cdi_device_nodes(path=p))
        if not common_device_nodes:
            return None

        # Device.appendix defaults to None and callers pass their own devices
        # in, so every read goes through `or {}`.
        is_a5 = any(
            get_ascend_cann_variant((dev.appendix or {}).get("arch_family"))
            == _A5_CANN_VARIANT
            for dev in devices
            if dev
        )

        mount_paths = [
            _HCCL_RANKTABLE_PATH,
            _HCCN_CONF_PATH,
            "/usr/local/Ascend/driver/topo",
            "/usr/local/Ascend/driver/lib64",
            "/usr/local/Ascend/driver/include",
            "/usr/local/dcmi",
            "/usr/local/bin/npu-smi",
            "/var/queue_schedule",
        ]

        if is_a5:
            # A5 loads libhccl_v2.so, which accepts a 2.0 ranktable only. A host
            # file left over from an A2 fleet is 1.0, and HCCL refuses it with
            # Config_Error_Ranktable(EI0014) rather than falling back, so every
            # multi-card init dies. Nothing here writes the file, so the only
            # lever is not mounting it -- verified by isolation: mounting only
            # this file into an otherwise-working container reproduces EI0014,
            # mounting only driver/topo does not.
            #
            # This is single-node evidence. A multi-node deployment does need a
            # ranktable; when that lands it has to be a 2.0 one, not this.
            #
            # Only GPUStack's own mount list is covered here. Under the Env
            # policy ascend-docker-runtime mounts the file itself, which
            # `warn_incompatible_ranktable` reports and cannot prevent.
            mount_paths.remove(_HCCL_RANKTABLE_PATH)

        common_mounts = []
        for p in mount_paths:
            cm = path_to_cdi_mount(
                path=p,
            )
            if cm:
                common_mounts.append(cm)

        if is_a5:
            for pattern in _A5_UB_MOUNT_PATTERNS:
                ub_mounts = glob_to_cdi_mounts(pattern=pattern)
                if not ub_mounts:
                    # Otherwise this surfaces later as a container that cannot
                    # reach the UB fabric.
                    logger.debug(
                        "No UB library matched %s, an A5 container will lack it",
                        pattern,
                    )
                common_mounts.extend(ub_mounts)

        cdi_devices: list[ConfigDevice] = []

        all_device_nodes = []

        for dev in devices:
            if not dev:
                continue

            container_device_nodes = []

            # The device node is numbered by the driver's physical id, which
            # Device.index no longer carries: it is the detector's enumeration
            # index, i.e. the DCMI logic id here. The two are different
            # numbers, so a device without a physical id is skipped instead of
            # addressed by the index, which would resolve to another NPU's
            # node. The detector already drops such a device; this guards the
            # devices a caller passes in.
            cdn_number = (dev.appendix or {}).get("physical_id")
            if cdn_number is None:
                continue
            cdn_path = f"/dev/davinci{cdn_number}"
            cdn = device_to_cdi_device_node(
                path=cdn_path,
            )
            if not cdn:
                continue
            all_device_nodes.append(cdn)
            container_device_nodes.append(cdn)

            # Add specific container edits for each device.
            cdi_devices.append(
                ConfigDevice(
                    name=str(dev.index),
                    container_edits=ConfigContainerEdits(
                        device_nodes=container_device_nodes,
                    ),
                ),
            )

        if not cdi_devices:
            return None

        # Add common container edits for all devices.
        if include_all_devices:
            cdi_devices.append(
                ConfigDevice(
                    name="all",
                    container_edits=ConfigContainerEdits(
                        device_nodes=all_device_nodes,
                    ),
                ),
            )

        runtime_env = manufacturer_to_runtime_env(self.manufacturer)

        return Config(
            kind=kind,
            devices=cdi_devices,
            container_edits=ConfigContainerEdits(
                env=[
                    f"{runtime_env}=void",
                ],
                device_nodes=common_device_nodes,
                mounts=common_mounts,
            ),
        )


def read_ranktable_version(path: str = _HCCL_RANKTABLE_PATH) -> str | None:
    """
    Read the ``version`` of the host ranktable file.

    The path is resolved as this process sees it, exactly as the mount list
    above resolves the paths it emits. Both therefore agree on whether the file
    exists.

    Args:
        path:
            The ranktable path to read.

    Returns:
        The declared version, or None if the file is absent, unreadable or not
        a JSON object carrying a string version.

    """
    try:
        content = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None

    if not isinstance(content, dict):
        return None

    version = content.get("version")
    return version if isinstance(version, str) else None


@cache
def warn_incompatible_ranktable() -> str | None:
    """
    Warn once if this A5 host carries a ranktable A5's HCCL will reject.

    ascend-docker-runtime mounts the host ranktable whenever the file is there
    -- its `addUBMount` is a bare `os.Stat` with no version check -- so under
    the default Env policy GPUStack cannot prevent the mount. Reporting is the
    only available action: the operator has to remove the file or replace it
    with a 2.0 one.

    Returns:
        The warning message emitted, or None if there is nothing to warn about.

    """
    # Ordered so a host without the file pays nothing: the file is absent on
    # almost every non-Ascend host, and detection is the expensive half.
    version = read_ranktable_version()
    if version is None or version == _A5_RANKTABLE_VERSION:
        return None

    devices = detect_devices(manufacturer=ManufacturerEnum.ASCEND)
    if not devices or not any(
        get_ascend_cann_variant((dev.appendix or {}).get("arch_family"))
        == _A5_CANN_VARIANT
        for dev in devices
        if dev
    ):
        # An older generation's own ranktable is correct for it.
        return None

    msg = (
        f"Host ranktable {_HCCL_RANKTABLE_PATH} declares version {version!r}, "
        f"but this A5 (Ascend 950) host needs {_A5_RANKTABLE_VERSION!r}. "
        f"Under the default Env policy ascend-docker-runtime mounts it on "
        f"presence and HCCL refuses it with Config_Error_Ranktable(EI0014), "
        f"failing every multi-card workload. Remove the file or replace it "
        f"with a {_A5_RANKTABLE_VERSION} table."
    )
    logger.warning(msg)
    return msg
