# This workflow runs for continuous integration (CI) of the project.

name: ci

permissions:
  actions: read
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "v*-dev"
    paths-ignore:
      - "!.github/workflows/ci.yml"
      - "pack/**"
      - "docs/**"
      - "tools/**"
      - "**.md"
      - "**.mdx"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.gif"
      - "**.webp"
  pull_request:
    branches:
      - "main"
      - "v*-dev"
    paths-ignore:
      - "!.github/workflows/ci.yml"
      - "pack/**"
      - "docs/**"
      - "tools/**"
      - "**.md"
      - "**.mdx"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.gif"
      - "**.webp"

jobs:
  # Execute CI jobs on Linux and macOS with different Python versions.
  ci:
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "linux"
          - "darwin"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ${{ matrix.os == 'linux' && 'ubuntu-22.04' || 'macos-14' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Make
        run: |
          make ci
        env:
          LINT_DIRTY: "true"
      - name: Upload Assets
        uses: actions/upload-artifact@v4
        with:
          retention-days: 5
          path: dist/*
          name: gputack-runtime-${{ matrix.os }}-${{ matrix.python-version }}
